-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS dailylogdb;
USE dailylogdb;

-- Users Table
CREATE TABLE IF NOT EXISTS User (
    id VARCHAR(191) PRIMARY KEY,
    email VARCHAR(191) UNIQUE NOT NULL,
    name VARCHAR(191),
    passwordHash VARCHAR(191) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Vehicles Table
CREATE TABLE IF NOT EXISTS Vehicle (
    id VARCHAR(191) PRIMARY KEY,
    name VARCHAR(191) NOT NULL,
    make VARCHAR(191),
    model VARCHAR(191),
    year INT,
    licensePlate VARCHAR(191),
    color VARCHAR(191),
    isActive BOOLEAN DEFAULT TRUE,
    displayOrder INT DEFAULT 0,
    userId VARCHAR(191) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

-- Vehicle Documents Table
CREATE TABLE IF NOT EXISTS VehicleDocument (
    id VARCHAR(191) PRIMARY KEY,
    filename VARCHAR(191) NOT NULL,
    filetype VARCHAR(191) NOT NULL,
    size INT NOT NULL,
    url VARCHAR(191) NOT NULL,
    vehicleId VARCHAR(191) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicleId) REFERENCES Vehicle(id) ON DELETE CASCADE
);

-- Fuel Entries Table
CREATE TABLE IF NOT EXISTS FuelEntry (
    id VARCHAR(191) PRIMARY KEY,
    date DATETIME NOT NULL,
    odometer DOUBLE NOT NULL,
    liters DOUBLE NOT NULL,
    costPerLiter DOUBLE NOT NULL,
    totalCost DOUBLE NOT NULL,
    fuelType VARCHAR(191) DEFAULT 'FULL',
    location VARCHAR(191),
    notes TEXT,
    parentEntry VARCHAR(191),
    odometerExtraKm DOUBLE DEFAULT 0,
    vehicleId VARCHAR(191) NOT NULL,
    userId VARCHAR(191) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicleId) REFERENCES Vehicle(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
    FOREIGN KEY (parentEntry) REFERENCES FuelEntry(id) ON DELETE SET NULL
);

-- Maintenance Costs Table
CREATE TABLE IF NOT EXISTS MaintenanceCost (
    id VARCHAR(191) PRIMARY KEY,
    date DATETIME NOT NULL,
    description VARCHAR(191) NOT NULL,
    cost DOUBLE NOT NULL,
    category VARCHAR(191) NOT NULL,
    odometer DOUBLE,
    location VARCHAR(191),
    notes TEXT,
    vehicleId VARCHAR(191) NOT NULL,
    userId VARCHAR(191) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (vehicleId) REFERENCES Vehicle(id) ON DELETE CASCADE,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

-- Security Questions Table
CREATE TABLE IF NOT EXISTS SecurityQuestion (
    id VARCHAR(191) PRIMARY KEY,
    question VARCHAR(191) NOT NULL,
    answerHash VARCHAR(191) NOT NULL,
    userId VARCHAR(191) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
    UNIQUE KEY unique_user_question (userId, question)
);

-- Expenses Table
CREATE TABLE IF NOT EXISTS Expense (
    id VARCHAR(191) PRIMARY KEY,
    date DATETIME NOT NULL,
    amount DOUBLE NOT NULL,
    category VARCHAR(191) NOT NULL,
    title VARCHAR(191) NOT NULL,
    description TEXT,
    paymentMethod VARCHAR(191) DEFAULT 'Cash',
    userId VARCHAR(191) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE,
    INDEX idx_user_date (userId, date),
    INDEX idx_category (category)
);

-- Settings Table
CREATE TABLE IF NOT EXISTS Settings (
    id VARCHAR(191) PRIMARY KEY,
    currency VARCHAR(191) DEFAULT 'BDT',
    dateFormat VARCHAR(191) DEFAULT 'MM/DD/YYYY',
    distanceUnit VARCHAR(191) DEFAULT 'km',
    volumeUnit VARCHAR(191) DEFAULT 'L',
    entriesPerPage INT DEFAULT 10,
    timezone VARCHAR(191) DEFAULT 'Asia/Dhaka',
    userId VARCHAR(191) UNIQUE NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);
